# Generated by Django 5.2.8 on 2025-11-08 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Competitors',
            new_name='Competitor',
        ),
        migrations.RenameModel(
            old_name='Throws',
            new_name='Throw',
        ),
    ]
