# Generated by Django 5.2.8 on 2025-11-13 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_rename_competitors_competitor_rename_throws_throw'),
    ]

    operations = [
        migrations.AddField(
            model_name='competitor',
            name='event',
            field=models.CharField(default='Main', help_text='Event name (e.g., Main, Qualifying)', max_length=100),
        ),
    ]
