# Generated by Django 5.2.8 on 2025-11-13 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0003_competitor_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='competitor',
            name='event',
            field=models.CharField(max_length=100),
        ),
    ]
