# Generated by Django 5.2.8 on 2025-11-13 10:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_alter_competitor_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='competitor',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tracker.event'),
        ),
    ]
