# Generated by Django 5.2.8 on 2025-11-13 11:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_event_alter_competitor_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='name',
        ),
        migrations.AddField(
            model_name='event',
            name='event_name',
            field=models.CharField(blank=True, choices=[('High Jump', 'High Jump'), ('Shot Put', 'Shot Put'), ('Javelin', 'Javelin'), ('Triple Jump', 'Triple Jump'), ('Long Jump', 'Long Jump'), ('Discus', 'Discus')], max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='gender',
            field=models.CharField(blank=True, choices=[('Boys', 'Boys'), ('Girls', 'Girls')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='grade',
            field=models.CharField(blank=True, choices=[('A', 'A Grade'), ('B', 'B Grade'), ('C', 'C Grade')], max_length=1, null=True),
        ),
    ]
