# Generated by Django 6.0.3 on 2026-03-07 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_remove_event_name_event_event_name_event_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='group',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
