# Generated by Django 6.0.3 on 2026-03-07 03:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0007_event_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='qualifying_distance',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
